-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 19:05:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SiteUsers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SiteUsers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SiteUsers` DEFAULT CHARACTER SET utf8 ;
USE `SiteUsers` ;

-- -----------------------------------------------------
-- Table `SiteUsers`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SiteUsers`.`Users` (
  `idUser` INT NOT NULL,
  `UserEmail` VARCHAR(45) NULL,
  `UserPassword` VARCHAR(45) NULL,
  `UserName` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

USE `SiteUsers` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `SiteUsers`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
